server {
    listen 5000;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    port_in_redirect off;
    absolute_redirect off;

    location /luka-aegis-fe/ {
        try_files $uri $uri/ /luka-aegis-fe/index.html;
    }

    # Redirect / to /Luka-aegis-fe/
    location = / {
        return 301 /luka-aegis-fe/;
    }

    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|map)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;
}
